#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_control_flow_attributes : enable

#include "scene.glsl"
#include "light_tree_data.glsl"

layout(binding = 0, set = 0) writeonly buffer light_link_buffer
{
    light_link array[];
} light_links;

layout(binding = 1, set = 0) writeonly buffer light_tree_leaf_buffer
{
    light_tree_node array[];
} leaf_data;

layout(binding = 2, set = 0) writeonly buffer sort_order_buffer
{
    uvec2 pairs[];
} sort_order;

layout(local_size_x = 256) in;

layout(push_constant) uniform push_constant_buffer
{
    vec4 bounds_min;
    vec4 bounds_inv_step;
    uint output_offset;
    uint key_shift;
    uint triangle_count;
    uint instance_id;
} pc;

void main()
{
    uint primitive = gl_GlobalInvocationID.x;
    if(primitive < pc.triangle_count)
    {
        instance i = instances.array[pc.instance_id];

        const uint mesh = i.buffer_index;

        uint index0 = indices[nonuniformEXT(mesh)].array[3*primitive+0];
        uint index1 = indices[nonuniformEXT(mesh)].array[3*primitive+1];
        uint index2 = indices[nonuniformEXT(mesh)].array[3*primitive+2];

        vec3 pos0 = vertex_position[nonuniformEXT(mesh)].array[index0];
        vec3 pos1 = vertex_position[nonuniformEXT(mesh)].array[index1];
        vec3 pos2 = vertex_position[nonuniformEXT(mesh)].array[index2];

        pos0 = APPLY_VERTEX_POS_TRANSFORM(i.model_to_world, pos0);
        pos1 = APPLY_VERTEX_POS_TRANSFORM(i.model_to_world, pos1);
        pos2 = APPLY_VERTEX_POS_TRANSFORM(i.model_to_world, pos2);

        const uint emission_texture = i.material.normal_emission_textures >> 16;
        vec3 emission = rgbe_to_rgb(i.material.emission);
        if(emission_texture != UNUSED_TEXTURE && (i.flags & ATTRIB_TEXTURE_UV) != 0)
        {
            vec2 uv0 = vertex_texture_uv[nonuniformEXT(mesh)].array[index0];
            vec2 uv1 = vertex_texture_uv[nonuniformEXT(mesh)].array[index1];
            vec2 uv2 = vertex_texture_uv[nonuniformEXT(mesh)].array[index2];

            vec2 uv = (uv0 + uv1 + uv2) / 3.0f;
            vec2 grad = max(abs(uv0 - uv), max(abs(uv1 - uv), abs(uv2 - uv)));
            emission *= textureGrad(textures[nonuniformEXT(emission_texture)], uv, grad, grad).rgb;
        }

        light_link ll;
        ll.instance_id = pc.instance_id;
        ll.primitive_id = primitive;
        light_links.array[pc.output_offset + primitive] = ll;

        vec3 min_pos = min(pos0, min(pos1, pos2));
        vec3 max_pos = max(pos0, max(pos1, pos2));

        light_tree_node leaf;

        leaf.center_radius = vec4(
            (min_pos + max_pos) * 0.5f,
            distance(min_pos, max_pos) * 0.5f
        );
        leaf.radius_brightness = vec4(
            (max_pos - min_pos) * 0.5f,
            luminance(emission) * triangle_area(pos0, pos1, pos2)
        );

        leaf_data.array[pc.output_offset + primitive] = leaf;

        vec3 center = (pos0+pos1+pos2) * (1.0f / 3.0f);
        ivec3 coord = clamp(
            ivec3((center - pc.bounds_min.xyz) * pc.bounds_inv_step.xyz),
            ivec3(0), ivec3(1<<10)-1
        );
        uint order = hilbert_encode_3d(coord);
        //uint order = morton_encode_3d(coord);

        sort_order.pairs[pc.output_offset + primitive] = uvec2(
            pc.output_offset + primitive,
            order << pc.key_shift
        );
    }
}
