#version 460

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0, rgba8) uniform readonly image2DArray in_color;
layout(binding = 1, rgba8) uniform writeonly image2D out_color;

layout(push_constant) uniform push_constant_buffer
{
    uvec2 output_size;
    uvec2 viewport_size;
    uvec2 viewport_count;
} control;

void main()
{
    uvec2 p = gl_GlobalInvocationID.xy;

    if(any(greaterThanEqual(p, control.output_size)))
        return;

    uvec2 xy = p / control.viewport_size;

    if(any(greaterThanEqual(xy, control.viewport_count)))
        return;

    uint layer = xy.x + xy.y * control.viewport_count.x;
    uvec2 q = p - xy * control.viewport_size;

    vec4 color = imageLoad(in_color, ivec3(q, layer));
    imageStore(out_color, ivec2(p), color);
}
