#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_debug_printf : enable

layout(push_constant) uniform push_constant_buffer
{
    vec4 base_offset;
    vec4 xyz_step;
    int cascade;
    int cascade_count;
    float interval_start;
    float interval_end;
    int c0_angular_resolution;
    int has_history;
    int ignore_missed_rays;
} pc;

layout(local_size_x = 8, local_size_y = 8) in;

//layout(binding = 0, r32f) uniform writeonly image2DArray cascade_target;
layout(binding = 0, rgba32f) uniform image2DArray cascade_target;
layout(binding = 1, r32f) uniform readonly image3D distance_field;

#include "radiance_cascades.glsl"

#define RAY_TRACING
#define USE_RAY_QUERIES
#define SCENE_SET 1
#include "scene.glsl"
#include "rt_common.glsl"

float get_distance(int cascade, ivec3 coord)
{
    // TODO: Needs mipmaps too.
    ivec3 transferred_coord = (coord << cascade);
    if(cascade > 0) transferred_coord += 1<<(cascade-1);
    return imageLoad(distance_field, transferred_coord).r;
}

// 0 = mesh
// 1 = point light
// -1 = miss
int get_intersection_info(
    vec3 ray_origin,
    vec3 ray_direction,
    hit_info payload,
    out vertex_data vd,
    out sampled_material mat
){
    float point_prob, triangle_prob, dir_prob, envmap_prob;
    get_nee_sampling_probabilities(point_prob, triangle_prob, dir_prob, envmap_prob);

    if(payload.instance_id >= 0)
    { // Mesh
        vd = get_interpolated_vertex(
            ray_direction, payload.barycentrics,
            payload.instance_id,
            payload.primitive_id
        );
        mat = sample_material(payload.instance_id, vd);
        mat.albedo.a = 1.0;

        return 0;
    }
    else if(payload.primitive_id >= 0)
    { // Point light
        point_light pl;
        pl = point_lights.lights[payload.primitive_id];

        vec3 hit_pos = ray_origin + ray_direction * payload.barycentrics.x;
        // No worries, radius cannot be zero -- we couldn't hit the light here
        // if it was!
        mat.emission = get_spotlight_intensity(pl, normalize(pl.pos-ray_origin)) * pl.color / (pl.radius * pl.radius * M_PI);
        vd.hard_normal = normalize(hit_pos-pl.pos);
        vd.pos = hit_pos;
        return 1;
    }
    else
    { // Miss
        if(pc.cascade+1 == pc.cascade_count)
        { // Only last cascade gets the environment lighting.
            vec4 color = scene_metadata.environment_factor;
            if(scene_metadata.environment_proj >= 0)
            {
                vec2 uv = vec2(0);
                uv.y = asin(-ray_direction.y)/M_PI+0.5f;
                uv.x = atan(ray_direction.z, ray_direction.x)/(2*M_PI)+0.5f;
                color.rgb *= texture(environment_map_tex, uv).rgb;
            }
            mat.emission = color.rgb;

            for(uint i = 0; i < scene_metadata.directional_light_count; ++i)
            {
                directional_light dl = directional_lights.lights[i];
                if(dl.dir_cutoff >= 1.0f)
                    continue;
                float visible = step(dl.dir_cutoff, dot(ray_direction, -dl.dir));
                vec3 color = visible * dl.color / (2.0f * M_PI * (1.0f - dl.dir_cutoff));
                mat.emission += color;
            }

            vd.pos = ray_origin + 1e9 * ray_direction;
            vd.hard_normal = vec3(0);
        }
        return -1;
    }
}

hit_info trace_primary_ray(
    uint seed,
    vec3 origin,
    vec3 dir,
    float len
){
    rayQueryEXT rq;
    rayQueryInitializeEXT(rq,
        tlas,
        gl_RayFlagsOpaqueEXT,
        0xFF,
        origin,
        0,
        dir,
        len
    );

    return trace_ray_query(rq, seed);
}

void main()
{
    ivec3 p = ivec3(gl_GlobalInvocationID.xyz);
    uint seed = 0; // TODO

    vec4 hit_color = vec4(0);//imageLoad(cascade_target, p);
    //if(pc.has_history != 0 && pc.ignore_missed_rays != 0 && hit_color.a == 0)
    //    return;

    bool first_cascade = pc.cascade == 0;
    bool last_cascade = pc.cascade+1 == pc.cascade_count;

    int angular_resolution = pc.c0_angular_resolution << pc.cascade;
    int next_angular_resolution = pc.c0_angular_resolution << (pc.cascade+1);

    ivec3 probe_index = ivec3(p.x/angular_resolution, p.y/angular_resolution, p.z);

    ivec2 map_texel = p.xy - probe_index.xy * angular_resolution;

    vec2 map_uv = (vec2(map_texel) + 0.5f) / angular_resolution;

    vec3 probe_dir = concentric_octahedral_mapping(map_uv);
    vec3 probe_origin = pc.base_offset.xyz + probe_index * pc.xyz_step.xyz;

#if 0
    vec3 ray_origin = probe_origin + probe_dir * pc.interval_start;
    vec3 ray_end = probe_origin + probe_dir * pc.interval_end;
#else
    // With bilinear & forking fixes
    ivec3 next_index = ivec3(probe_index.xyz/2);
    vec3 next_origin = pc.base_offset.xyz + 0.5f * pc.xyz_step.xyz + next_index * pc.xyz_step.xyz * 2.0f;
    if(last_cascade) next_origin = probe_origin;

    vec2 prev_map_uv = (vec2(map_texel/2) + 0.5f) / (angular_resolution/2);
    vec3 prev_dir = concentric_octahedral_mapping(prev_map_uv);
    if(first_cascade) prev_dir = probe_dir;

    vec3 ray_origin = probe_origin + prev_dir * pc.interval_start;
    vec3 ray_end = next_origin + probe_dir * pc.interval_end;
#endif

    vec3 ray_dir = ray_end - ray_origin;
    float ray_len = length(ray_dir);
    ray_dir /= ray_len;

    float dist = get_distance(pc.cascade, probe_index);
    if(ray_len < dist || max(pc.xyz_step.x, max(pc.xyz_step.y, pc.xyz_step.z)) < dist)
    {
        // TODO: This can be commented out for extra perf, it just needs to be
        // there for visualization to work when a surface isn't in vicinity.
        imageStore(cascade_target, p, vec4(0,0,0,0));
        return;
    }

    hit_color = vec4(0);

    hit_info hi = trace_primary_ray(seed, ray_origin, ray_dir, ray_len);
    vertex_data vd;
    sampled_material mat;
    int hit_type = get_intersection_info(ray_origin, ray_dir, hi, vd, mat);
    if(hit_type >= 0)
    { // Hit an emissive surface.
        //hit_color.rgb = mat.emission;
        hit_color.rgb = mat.albedo.rgb + mat.emission;
        hit_color.a = 1.0f;
    }
    /*
    if(hit_type == 0)
    {
        hit_color.rgb = vec3(1,0,0);
        hit_color.a = 1.0f;
    }
    else if(hit_type == 1)
    {
        hit_color.rgb = vec3(0,1,0);
        hit_color.a = 1.0f;
    }
    */
    else if(hit_type == -1 && last_cascade)
    { // Hit sky
        // TODO read skybox
        hit_color.rgb = mat.emission;
        hit_color.a = 1.0f;
    }

    imageStore(cascade_target, p, hit_color);
}
