#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_ray_query : enable

layout(local_size_x = 8, local_size_y = 8) in;

layout(push_constant) uniform push_constant_buffer
{
    int display_w;
    int display_h;
    int cascade_w;
    int cascade_h;
    int cascade;
    int layer;
} pc;

layout(binding = 0, rgba32f) uniform writeonly image2D target;
layout(binding = 1, r32f) uniform readonly image3D distance_field;
#define SCENE_SET 1
#define GET_INTERSECTION_TRIANGLE_POSITIONS
#define RAY_TRACING
#define USE_RAY_QUERIES
#include "scene.glsl"
#include "rt_common.glsl"
#define printf debugPrintfEXT
#define RADIANCE_CASCADES_SET 2
#include "radiance_cascades.glsl"

void main()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);

    if(p.x < pc.display_w && p.y < pc.display_h)
    {
#if 1
        vec2 uv = vec2(vec2(p) + 0.5f) / vec2(pc.display_w, pc.display_h);

        // Staircase
        vec3 origin = vec3(-0.694497, 1.420297, -3.715099);
        vec3 normal = vec3(0.099632, 0.130290, 0.986457);
        vec3 view = vec3(-0.120005, -0.158434, -0.980050);
        float roughness = 0.2;

        // Classroom
        /*
        vec3 origin = vec3(1.996950, 2.204355, -1.412573);
        vec3 normal = vec3(0.025848, -0.999660, -0.003543);
        vec3 view = vec3(-0.138051, 0.986518, 0.087889);
        float roughness = 0.25;
        */

        mat3 tbn = create_tangent_space(normal);

        float lat = asin(1-uv.y*2);
        float lon = (1-uv.x) * M_PI;
        vec3 dir = mat3(tbn[1], tbn[2], tbn[0]) * vec3(cos(lat)*cos(lon), cos(lat)*sin(lon), sin(lat));


        //if(p.x == 960 && p.y == 540)
        //    printf("%f, %f, %f\n", dir.x, dir.y, dir.z);

        float pdf = radiance_cascades_pdf(origin, normal, view, false, roughness, 0.04, 1.0f, dir);

        /*
        rayQueryEXT rq;
        rayQueryInitializeEXT(rq,
            tlas,
            gl_RayFlagsNoneEXT,
            0xFF,
            origin,
            0.001f,
            dir,
            1000.0f
        );

        uint seed = 0;
        hit_info payload = trace_ray_query(rq, seed);
        if(payload.instance_id < 0) payload.hit_t = 1000.0f;
        pdf = 1.0f / (1.0f + payload.hit_t);
        */

        imageStore(target, p, vec4(pdf,pdf,pdf, 1.0f));
#else
        const camera_data cam = camera.pairs[gl_GlobalInvocationID.z].current;
        vec3 origin;
        vec3 dir;
        get_camera_ray(cam, ivec2(p.x, pc.display_h-p.y), vec2(pc.display_w, pc.display_h), vec2(0.5), origin, dir);

        uvec4 seed = uvec4(p.x, p.y, 1025, 12);
        vec3 col = query_radiance_cascades(origin, dir, seed);

        imageStore(target, p, vec4(col, 1.0f));
#endif
    }
}
