#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_debug_printf : enable

layout(local_size_x = 8, local_size_y = 8) in;

//layout(binding = 0, r32f) uniform writeonly image3D cascade_target;
layout(binding = 0, rgba32f) uniform image3D cascade_target;
layout(binding = 1, r32f) uniform readonly image3D distance_field;

#include "radiance_cascades.glsl"

#define RAY_TRACING
#define USE_RAY_QUERIES
#define GET_INTERSECTION_TRIANGLE_POSITIONS
#define SCENE_SET 1
#define SCENE_RASTER_SET 2
#include "scene.glsl"
#include "rt_common.glsl"
#include "scene_raster.glsl"

layout(push_constant) uniform push_constant_buffer
{
    vec4 base_offset;
    vec4 xyz_step;
    vec2 jitter;
    int cascade;
    int cascade_count;
    float interval_start;
    float interval_end;
    int c0_angular_resolution;
    int cascade_size;
    shadow_mapping_parameters sm_params;
    float ambient;
} pc;

#define SHADOW_MAPPING_PARAMS pc.sm_params
#define SHADOW_MAPPING_SCREEN_COORD ivec2(0)
#include "shadow_mapping.glsl"

float get_distance(int cascade, ivec3 coord)
{
    // TODO: Needs mipmaps too.
    ivec3 transferred_coord = (coord << cascade);
    if(cascade > 0) transferred_coord += 1<<(cascade-1);
    return imageLoad(distance_field, transferred_coord).r;
}

hit_info trace_primary_ray(
    uint seed,
    vec3 origin,
    vec3 dir,
    float len
){
    rayQueryEXT rq;
    rayQueryInitializeEXT(rq,
        tlas,
        gl_RayFlagsOpaqueEXT,
        0xFF,
        origin,
        0,
        dir,
        len
    );

    return trace_ray_query(rq, seed);
}

vec2 simple_shade(vec3 ray_origin, vec3 ray_direction, hit_info info)
{
    if(info.instance_id >= 0)
    { // Hit an emissive surface.
        vec3 normal = normalize(cross(
            info.positions[1]- info.positions[0],
            info.positions[2]- info.positions[0]
        ));
        if(dot(normal, ray_direction) > 0) normal = -normal;
        vec3 pos = ray_origin + info.hit_t * ray_direction;
        instance o = instances.o[info.instance_id];
        vec3 color = o.mat.albedo_factor.rgb;
        if(o.mat.albedo_tex_id >= 0)
        {
            // Only fetch material info for textured surfaces.
            ivec3 i = ivec3(
                indices[nonuniformEXT(info.instance_id)].i[3*info.primitive_id+0],
                indices[nonuniformEXT(info.instance_id)].i[3*info.primitive_id+1],
                indices[nonuniformEXT(info.instance_id)].i[3*info.primitive_id+2]
            );
            vertex v0 = vertices[nonuniformEXT(info.instance_id)].v[i.x];
            vertex v1 = vertices[nonuniformEXT(info.instance_id)].v[i.y];
            vertex v2 = vertices[nonuniformEXT(info.instance_id)].v[i.z];
            vec3 b = vec3(1.0f - info.barycentrics.x - info.barycentrics.y, info.barycentrics);
            vec2 uv = v0.uv * b.x + v1.uv * b.y + v2.uv * b.z;
            vec3 tex_col = sample_texture(o.mat.albedo_tex_id, uv).rgb;
            tex_col = inverse_srgb_correction(tex_col);
            color *= tex_col;
        }

        vec3 emission = o.mat.emission_factor.rgb + pc.ambient * color;

        // Shade as if it was a diffuse surface.
        for(uint i = 0; i < scene_metadata.directional_light_count; ++i)
        {
            directional_light dl = directional_lights.lights[i];
            float shadow = 1.0f;
            if(dl.shadow_map_index >= 0 && dot(normal, -dl.dir) > 0)
                shadow = calc_directional_shadow(
                    dl.shadow_map_index, pos, normal, -dl.dir
                );
            if(dot(normal, dl.dir) > 0)
                shadow = 0.0f;

            emission += color * shadow * dl.color * max(dot(normal, -dl.dir), 0) / M_PI;
        }

        POINT_LIGHT_FOR_BEGIN(v.pos)
            point_light pl = point_lights.lights[item_index];
            vec3 light_dir;
            float light_dist;
            vec3 light_color;
            get_point_light_info(pl, pos, light_dir, light_dist, light_color);

            float shadow = 1.0f;
            if(pl.shadow_map_index >= 0 && dot(normal, light_dir) > 0)
                shadow = calc_point_shadow(
                    pl.shadow_map_index, pos, normal, light_dir
                );
            if(dot(normal, light_dir) < 0)
                shadow = 0.0f;

            emission += color * shadow * light_color * max(dot(normal, light_dir), 0) / M_PI;
        POINT_LIGHT_FOR_END

        return vec2(rgb_to_luminance(emission), 1.0f);
    }
    else if(info.primitive_id >= 0)
    { // Point light
        return vec2(0.0f, 1.0f);
        /*
        point_light pl = point_lights.lights[info.primitive_id];

        // No worries, radius cannot be zero -- we couldn't hit the light here
        // if it was!
        vec3 emission = get_spotlight_intensity(pl, ray_direction) * pl.color / (pl.radius * pl.radius * M_PI);
        return vec2(rgb_to_luminance(emission), 1.0f);
        */
    }
    else if(pc.cascade+1 == pc.cascade_count)
    { // Only last cascade gets the environment lighting.
        return vec2(0.0f, 1.0f);
        /*
        vec4 color = scene_metadata.environment_factor;
        if(scene_metadata.environment_proj >= 0)
        {
            vec2 uv = vec2(0);
            uv.y = asin(-ray_direction.y)/M_PI+0.5f;
            uv.x = atan(ray_direction.z, ray_direction.x)/(2*M_PI)+0.5f;
            color.rgb *= texture(environment_map_tex, uv).rgb;
        }
        vec3 emission = color.rgb;

        for(uint i = 0; i < scene_metadata.directional_light_count; ++i)
        {
            directional_light dl = directional_lights.lights[i];
            if(dl.dir_cutoff >= 1.0f)
                continue;
            float visible = step(dl.dir_cutoff, dot(ray_direction, -dl.dir));
            vec3 color = visible * dl.color / (2.0f * M_PI * (1.0f - dl.dir_cutoff));
            emission += color;
        }

        return vec2(rgb_to_luminance(emission), 1.0f);
        */
    }
    return vec2(0);
}

void main()
{
    ivec3 p = ivec3(gl_GlobalInvocationID.xyz);
    uint seed = 0; // TODO

    bool first_cascade = pc.cascade == 0;
    bool last_cascade = pc.cascade+1 == pc.cascade_count;

    int angular_resolution = pc.c0_angular_resolution << pc.cascade;
    int next_angular_resolution = pc.c0_angular_resolution << (pc.cascade+1);

    ivec3 probe_index = ivec3(p.xy%pc.cascade_size, p.z);
    ivec2 map_texel = p.xy/pc.cascade_size;

    vec2 map_uv = (vec2(map_texel) + pc.jitter) / angular_resolution;

    vec3 probe_dir = concentric_octahedral_mapping(map_uv);
    vec3 probe_origin = pc.base_offset.xyz + probe_index * pc.xyz_step.xyz;

#if 0
    vec3 ray_origin = probe_origin + probe_dir * pc.interval_start;
    vec3 ray_end = probe_origin + probe_dir * pc.interval_end;
#else
    // With bilinear & forking fixes
    ivec3 next_index = ivec3(probe_index.xyz/2);
    vec3 next_origin = pc.base_offset.xyz + 0.5f * pc.xyz_step.xyz + next_index * pc.xyz_step.xyz * 2.0f;
    if(last_cascade) next_origin = probe_origin;

    vec2 prev_map_uv = (vec2(map_texel/2) + pc.jitter) / (angular_resolution/2);
    vec3 prev_dir = concentric_octahedral_mapping(prev_map_uv);
    if(first_cascade) prev_dir = probe_dir;

    vec3 ray_origin = probe_origin + prev_dir * pc.interval_start;
    vec3 ray_end = next_origin + probe_dir * pc.interval_end;
#endif

    vec3 ray_dir = ray_end - ray_origin;
    float ray_len = length(ray_dir);
    ray_dir /= ray_len;

    float dist = get_distance(pc.cascade, probe_index);
    if(ray_len < dist || max(pc.xyz_step.x, max(pc.xyz_step.y, pc.xyz_step.z)) < dist)
    {
        // TODO: This can be commented out for extra perf, it just needs to be
        // there for visualization to work when a surface isn't in vicinity.
        imageStore(cascade_target, p, vec4(0,0,1,1));
        return;
    }

    hit_info hi = trace_primary_ray(seed, ray_origin, ray_dir, ray_len);
    vertex_data vd;

    vec2 hit_color = simple_shade(ray_origin, ray_dir, hi);

    imageStore(cascade_target, p, vec4(hit_color,0,0));
}
