#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_debug_printf : enable

#define SCENE_SET 1

layout(push_constant) uniform push_constant_buffer
{
    vec4 base_offset;
    vec4 xyz_step;
    int cascade;
    float interval_start;
    float interval_end;
} pc;

layout(local_size_x = 8, local_size_y = 8) in;

void main()
{
    // TODO
}
