#version 460
#line 3
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_debug_printf : enable

#include "restir.glsl"

layout(push_constant) uniform push_constant_buffer
{
    restir_config config;
    uvec2 display_size;
    uint sample_index;
    uint camera_index;
    uint accumulated_samples;
    uint initialize_output;
    uint accumulate_color;
    uint update_sample_color;
} pc;

layout(binding = 14) uniform sampler2D emission_tex;

// These buffers are SUPER overloaded.
// These names are for demodulated output, but they also contain demodulated
// input or non-demodulated input/output.
layout(binding = 15, rgba32f) uniform image2D out_color;

layout(binding = 16, rg32ui) readonly uniform uimage2D spatial_selection;
layout(binding = 17, rgba32f) readonly uniform image2DArray mis_data;
layout(binding = 18, rgba32f) readonly uniform image2DArray spatial_candidates;
layout(binding = 19, rgba32f) uniform image2D in_color;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

#include "restir_core.glsl"

void finish_output_color(ivec2 p, reservoir[3] r_rgb, vec4 out_value, vec3 sc)
{
    [[unroll]] for(int i = 0; i < 3; ++i)
        write_reservoir(r_rgb[i], ivec3(p, i), pc.display_size);

    if(pc.update_sample_color != 0)
        imageStore(in_color, p, out_value);
    else
    {
        imageStore(out_color, p, vec4(sc, 1.0f));
    }

}

void main()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);

    if(any(greaterThanEqual(p, pc.display_size)))
        return;

    uvec4 seed = uvec4(p, pc.camera_index, pc.sample_index);
    pcg4d(seed);

    camera_data cam = camera.pairs[pc.camera_index].current;
    vec3 origin = cam.origin.xyz;

    reservoir[3] r_rgb;
    [[unroll]] for(int i = 0; i < 3; ++i)
        init_reservoir(r_rgb[i]);

    domain canonical_domain;
    bool miss = read_domain(cam, p, canonical_domain);

    uvec4 selection = imageLoad(spatial_selection, p);
    const uint candidate_key = selection.r;

    vec3 canonical_resampling_mis_weight = 
        vec3(uintBitsToFloat(selection).g, uintBitsToFloat(selection).b, uintBitsToFloat(selection).w);

         if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
             debugPrintfEXT("canonical_mis_weight = %f, %f, %f", canonical_resampling_mis_weight.r, canonical_resampling_mis_weight.g, canonical_resampling_mis_weight.b);


    vec3 canonical_emission = sample_gbuffer_emission(emission_tex, p);
    vec3 sc = canonical_emission;
    vec4 canonical_value = imageLoad(in_color, p);
    vec4 out_value = canonical_value;

    const float max_plane_dist = get_frustum_size(cam, canonical_domain.pos);

    if(miss)
    {
        // Missed scene, so mark invalid so that temporal reprojection skips
        // this pixel.
        [[unroll]] for(int i = 0; i < 3; ++i)
            write_reservoir(r_rgb[i], ivec3(p,i), pc.display_size);

        return;
    }

    if(MAX_SPATIAL_SAMPLES == 0)
    {
        reservoir[3] canonical_pixel;
        [[unroll]] for(int i = 0; i < 3; ++i)
        {
            canonical_pixel[i] = read_reservoir(ivec3(p,i), pc.display_size);
            sc[i] += canonical_value[i] * max(canonical_pixel[i].ucw, 0.0f);

//            if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
//                debugPrintfEXT("spatial: %i, %f", i, canonical_pixel[i].ucw);
        }


        finish_output_color(p, canonical_pixel, out_value, sc);
        return;
    }

    ivec3 chosen_i = ivec3(0.0f);
    vec3 chosen_jacobian_part = vec3(0.0f);

    [[unroll]] for(int reservoir_index = 0; reservoir_index < 3; ++reservoir_index)
    {
        [[unroll]] for(int candidate_index = 0; candidate_index < MAX_SPATIAL_SAMPLES; ++candidate_index)
        {
            int i = candidate_index * 3 + reservoir_index;
            vec4 mis = imageLoad(mis_data, ivec3(p, i));
            vec4 value = imageLoad(spatial_candidates, ivec3(p, i));


            float confidence = mis.r;
            float target_function_value = mis.a;
            float resampling_mis_weight = mis.g;


            float resampling_weight = resampling_mis_weight * target_function_value;
            sc[reservoir_index] += value[reservoir_index] * resampling_mis_weight;

//            if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
//                debugPrintfEXT("resampling data %i %f", reservoir_index, target_function_value);

            if(update_reservoir(
                generate_single_uniform_random(seed.x),
                r_rgb[reservoir_index],
                target_function_value, 
                resampling_weight,
                confidence
            )){

                if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
                    debugPrintfEXT("%i added %f resampling_weight", reservoir_index, resampling_weight);

                chosen_i[reservoir_index] = candidate_index;
                chosen_jacobian_part[reservoir_index] = mis.b;
                out_value[reservoir_index] = value[reservoir_index];
            }
        }
    }
    //[[unroll]] for(int i = 0; i < 3; ++i)
//        if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
//            debugPrintfEXT("weight_sum for %i: %f", i, r_rgb[i].sum_weight);


    reservoir[3] canonical_pixel_rgb;
    [[unroll]] for(int ind = 0; ind < 3; ++ind)
        canonical_pixel_rgb[ind] = read_reservoir(ivec3(p, ind), pc.display_size);

    // Insert the pixel's own reservoir from the previous step. This must be
    // done last so that pairwise MIS works (we accumulate
    // canonical_resampling_mis_weight previously)

    [[unroll]] for(int ind = 0; ind < 3; ++ind)
    {
        float resampling_weight =
            canonical_resampling_mis_weight[ind] *
            canonical_pixel_rgb[ind].target_function_value *
            max(canonical_pixel_rgb[ind].ucw, 0); // w_i
                                                  //
//        if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
//            debugPrintfEXT("%f = %f * %f * %f", resampling_weight, canonical_resampling_mis_weight[ind], canonical_pixel_rgb[ind].target_function_value, canonical_pixel_rgb[ind].ucw);

        sc[ind] += canonical_value[ind] * canonical_resampling_mis_weight[ind] * max(canonical_pixel_rgb[ind].ucw, 0);

//        if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
//            debugPrintfEXT("%f, %f, %f", canonical_value[ind], canonical_resampling_mis_weight[ind], canonical_pixel_rgb[ind].ucw);
        
        if(update_reservoir(
            generate_single_uniform_random(seed.x), r_rgb[ind],
            canonical_pixel_rgb[ind].target_function_value,
            resampling_weight,
            canonical_pixel_rgb[ind].confidence
        )){
            r_rgb[ind].output_sample = canonical_pixel_rgb[ind].output_sample;
            out_value[ind] = canonical_value[ind];
        }
        else
        {
            mat3 flat_tbn = create_tangent_space(canonical_domain.flat_normal);
            spatial_candidate_sampler scs = init_spatial_candidate_sampler(
                cam, canonical_domain.pos, flat_tbn, max_plane_dist
            );
            ivec2 s = spatial_candidate_pos(
                candidate_key, p, ivec2(pc.display_size), scs,
                pc.camera_index, pc.sample_index, chosen_i[ind]
            );
            r_rgb[ind].output_sample = read_reservoir(ivec3(s, ind), pc.display_size).output_sample; // X_i
            r_rgb[ind].output_sample.base_path_jacobian_part = chosen_jacobian_part[ind];
        }

        // Update UCW
        if(r_rgb[ind].target_function_value > 0)
        {
            r_rgb[ind].ucw = r_rgb[ind].sum_weight/r_rgb[ind].target_function_value;
//            if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
//                debugPrintfEXT("%f = %f / %f", r_rgb[ind].ucw, r_rgb[ind].sum_weight, r_rgb[ind].target_function_value);
        }

    }
//    if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
//        debugPrintfEXT("%f, %f %f", sc.x, sc.y, sc.z);

    if(all(equal(pc.config.display_size.xy / 2, gl_GlobalInvocationID.xy)))
        debugPrintfEXT("");


    finish_output_color(p, r_rgb, out_value, sc);

}
