#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

#include "rt_common.glsl"

hitAttributeEXT vec3 attribs;

void main()
{
    point_light pl = point_lights.lights[gl_PrimitiveID];
    float hit = get_point_light_hit_t(pl, gl_WorldRayOriginEXT, gl_WorldRayDirectionEXT);
    if(hit > 0)
        reportIntersectionEXT(hit, 0);
}
