#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(binding = 0, scalar) uniform tonemap_info_buffer
{
    ivec2 size;
    int alpha_grid_background;
    float exposure;
    float gamma;
} info;

vec4 tonemap(vec4 col)
{
    vec3 c = clamp(col.rgb * info.exposure, vec3(0), vec3(1000));
    return vec4(c/(1+c), col.a);
}

#include "tonemap.glsl"
