#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_debug_printf : enable

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(binding = 0) uniform writeonly uimage3D occupancy;

void main()
{
    ivec3 p = ivec3(gl_GlobalInvocationID.xyz);
    imageStore(occupancy, p, uvec4(0));
}
